name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20.1
      - uses: open-policy-agent/setup-opa@v2
        with:
          version: latest
      - uses: golangci/golangci-lint-action@v3
      - run: opa check --strict bundle
      - run: opa test --bundle bundle
      - run: go test ./...
      - run: go build
