name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.20.1
      - uses: open-policy-agent/setup-opa@v2
        with:
          version: latest
      - run: opa test policy data
      - run: go build
